# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: back

jobs:
  test:
    environment: CI
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: back/package-lock.json
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Run tests
      env: 
        SECRET: ${{ secrets.SECRET }}
        TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
        PORT: ${{ secrets.PORT }}
      run: |
        npm ci
        npm test
