# This workflow will do a clean install of node dependencies, cache/restore them and run tests.
# If tests are all passing, it will rebuild the front

name: Front end CI

on:
  push:
    branches: [ main ]
    paths:
      - 'front/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'front/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: front

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Run linter and tests
      run: |
        npm ci
        npm run lint
        npm test
  build:
    needs: test

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Rebuild front
      run: |
        npm ci
        npm run build:ui
    - name: Commit new front end files
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'github-action@users.noreply.github.com'
        git add build/
        git commit -m "Rebuilt front end"
        git push
    

