# This workflow will do a clean install of node dependencies, cache/restore them and run tests.
# If tests are all passing, it will rebuild the front

name: Front end CI

on:
  push:
    paths:
      - 'front/**'

defaults:
  run:
    working-directory: front

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Use NodeJS 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Install needed packages
      run: npm ci
    - name: Run linter
      run: npm run lint
    - name: Run tests
      run: npm run test:ci
    - name: Rebuild front
      run: npm run build:ui
    - name: Checking if theres anything to commit
      id: check_changes
      # Returns number of lines of git status --porcelain, each line should be a change.
      # 0 lines means no changes to commit
      # head -255 is a safeguard to avoid errors in the weird case of having more than 255 lines
      run: | 
        echo "::set-output name=changes::$(git status --porcelain | head -255 | wc -l)"
    - name: Commit new front end files
      if: ${{ steps.check_changes.outputs.changes != 0 }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add ../back/build/
        git commit -m "Rebuilt front end"
        git push
    

