# This workflow will do a clean install of node dependencies, cache/restore them and run tests.
# If tests are all passing, it will rebuild the front

name: Front end CI

on:
  push:
    paths:
      - 'front/**'

defaults:
  run:
    working-directory: front

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Use NodeJS 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Install needed packages
      run: npm ci
    - name: Run linter
      run: npm run lint
    - name: Run tests
      run: npm run test:ci
    - name: Rebuild front
      run: npm run build:ui
    - name: Commit new front end files
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'github-action@users.noreply.github.com'
        git add build/
        git commit -m "Rebuilt front end"
        git push
    

